#version: "3.9"
#
#services:
#  db:
#    image: postgres:15-alpine
#    restart: always
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#    ports:
#      - '5432:5432'
#    environment:
#      - POSTGRES_DB=job
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=1000
#  web:
#    build:
#      context: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    environment:
#      - POSTGRES_NAME=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=1000
#    depends_on:
#      - db
#
#volumes:
#  db:
#    driver: local


#    image: postgres:15-alpine
#    restart: always
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#    ports:
#      - '5432:5432'
#    environment:
#      - POSTGRES_DB=job
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=1000
#  web:
#    build:
#      context: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#
#volumes:
#  db:
#    driver: local

version: '3.8'

services:
  web:
    build:
      context: .
      command: python manage.py runserver 0.0.0.0:8000
    volumes:
       - ./data/db:/var/lib/postgresql/data
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1000
      - POSTGRES_DB=job

volumes:
  postgres_data: